export const PK_TYPES_SEND = {
    CONNECTION_CLOSED : "CONNECTION_CLOSED",
    CONNECTION_ERROR : "CONNECTION_ERROR",
    SING_IN : "SING_IN",
    SING_UP : "SING_UP",
    SING_OUT : "SING_OUT",
    CREATE_PLACE : "CREATE_PLACE",
    GET_PLACE : "GET_PLACE",
};


export const PK_TYPES_SERVER_SEND = {
    CONNECTION_SUCCEED : "CONNECTION_SUCCEED",
};

export const PK_TYPES_CLIENT_SEND = {

};
